name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 59a09ef2-fa43-4268-998b-ca88b1f8f6f1
          SONAR_TOKEN: 811c9a490983734401ba4e491eaefc8bfa7281de
